### ISSUE TITLE
Error generating types for VS Code 

### ISSUE THREAD

**Issue by NatElkins** [glutinum-org/cli#152]
Running the following:

`npx @glutinum/cli ./node_modules/@types/vscode/index.d.ts`

Results in the following error:

```
Generating binding file for ./node_modules/@types/vscode/index.d.ts
/Users/nat/Projects/fable-vscode-bindings/node_modules/typescript/lib/typescript.js:16488
  return getTextOfNodeFromSourceText(sourceFile.text, node, includeTrivia);
                                                ^

TypeError: Cannot read properties of undefined (reading 'text')
    at getSourceTextOfNodeFromSourceFile (/Users/nat/Projects/fable-vscode-bindings/node_modules/typescript/lib/typescript.js:16488:49)
    at getTextOfNode (/Users/nat/Projects/fable-vscode-bindings/node_modules/typescript/lib/typescript.js:16516:10)
    at entityNameToString (/Users/nat/Projects/fable-vscode-bindings/node_modules/typescript/lib/typescript.js:17285:56)
    at formatJSDocLink (/Users/nat/Projects/fable-vscode-bindings/node_modules/typescript/lib/typescript.js:15171:28)
    at /Users/nat/Projects/fable-vscode-bindings/node_modules/typescript/lib/typescript.js:15167:138
    at Array.map (<anonymous>)
    at Object.getTextOfJSDocComment (/Users/nat/Projects/fable-vscode-bindings/node_modules/typescript/lib/typescript.js:15167:85)
    at file:///Users/nat/Projects/fable-vscode-bindings/node_modules/@glutinum/cli/dist/Glutinum.Converter/Reader/Documentation.js:110:70
    at file:///Users/nat/Projects/fable-vscode-bindings/node_modules/@glutinum/cli/dist/fable_modules/fable-library-js.4.14.0/Seq.js:378:20
    at Enumerator_FromFunctions$1.next (file:///Users/nat/Projects/fable-vscode-bindings/node_modules/@glutinum/cli/dist/fable_modules/fable-library-js.4.14.0/Seq.js:251:32)
 ```
    
Curiously when I paste it into the web tool it seems to work:

<img width="1726" alt="image" src="https://github.com/user-attachments/assets/56d42e01-8788-471c-bebd-9b7f1604f1fd">

**Comment by NatElkins** [comment]
I just gave this try using a local build of latest main and I wasn't able to reproduce.  Just wanted to note.  I'll leave it open until 0.12.0 is published to npm to confirm.

**Comment by NatElkins** [comment]
Hm I still seem to get it with 0.12.

```
➜  fable-vscode-bindings2 npx @glutinum/cli --version
0.12.0
➜  fable-vscode-bindings2 npx @glutinum/cli ./node_modules/@types/vscode/index.d.ts --out-file ./src/Fable.VsCode/Bindings.fs
Generating binding file for ./node_modules/@types/vscode/index.d.ts
/Users/nat/Projects/fable-vscode-bindings2/node_modules/typescript/lib/typescript.js:16548
  return getTextOfNodeFromSourceText(sourceFile.text, node, includeTrivia);
                                                ^

TypeError: Cannot read properties of undefined (reading 'text')
    at getSourceTextOfNodeFromSourceFile (/Users/nat/Projects/fable-vscode-bindings2/node_modules/typescript/lib/typescript.js:16548:49)
    at getTextOfNode (/Users/nat/Projects/fable-vscode-bindings2/node_modules/typescript/lib/typescript.js:16576:10)
    at entityNameToString (/Users/nat/Projects/fable-vscode-bindings2/node_modules/typescript/lib/typescript.js:17407:56)
    at formatJSDocLink (/Users/nat/Projects/fable-vscode-bindings2/node_modules/typescript/lib/typescript.js:15211:28)
    at /Users/nat/Projects/fable-vscode-bindings2/node_modules/typescript/lib/typescript.js:15207:138
    at Array.map (<anonymous>)
    at Object.getTextOfJSDocComment (/Users/nat/Projects/fable-vscode-bindings2/node_modules/typescript/lib/typescript.js:15207:85)
    at file:///Users/nat/Projects/fable-vscode-bindings2/node_modules/@glutinum/cli/dist/Glutinum.Converter/Reader/Documentation.js:110:70
    at file:///Users/nat/Projects/fable-vscode-bindings2/node_modules/@glutinum/cli/dist/fable_modules/fable-library-js.4.14.0/Seq.js:378:20
    at Enumerator_FromFunctions$1.next (file:///Users/nat/Projects/fable-vscode-bindings2/node_modules/@glutinum/cli/dist/fable_modules/fable-library-js.4.14.0/Seq.js:251:32)

Node.js v20.17.0
```

**Comment by NatElkins** [comment]
And it happens after downgrading to tsc 4.9.5 as well (from 5.7.2).

**Comment by NatElkins** [comment]
Just as a quick follow-up, it appears to be coming from this code in `Documentation.fs`:

```fsharp
let jsDocTags =
        jsDocTags
        |> Seq.choose (fun tag ->
            match tag.kind with
            | Ts.SyntaxKind.JSDocReturnTag ->
                match tag.comment with
                | Some comment ->
                    // This line here, ts.getTextOfJSDocComment
                    ts.getTextOfJSDocComment comment
                    |> Option.defaultValue ""
                    |> GlueComment.Returns
                    |> Some
                | None -> None
```

It's line 31.  I used this little tool to figure it out: https://pastcompute.github.io/ScriptMapper/

**Comment by MangelMaxime** [comment]
Hum, strangely this bug only happens when using the published NPM package.

- Web tool works
- Local CLI tools works

The problem is coming from TypeScript, which doesn't seems to be able to find the source file of a Node for some reason.

**Comment by MangelMaxime** [comment]
Problems seems to be caused by instructions like `{@link TextLine line}`

**Comment by johnW-ret** [comment]
In my case I'm pretty sure it's [an unsupported feature](https://github.com/glutinum-org/cli/blob/1cee8b0e0d5643082b2a1c04954fe7cf3d530e80/src/Glutinum.Converter/Reader/IndexedAccessType.fs#L29) but for anyone else who finds this issue I want to resurface that I am getting the above error from the CLI with indexed access types in [@typed/hast](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/27f61414c06e74b5add253f03db911914919fc01/types/hast/index.d.ts)

The web version provides more helpful error messages.

**Comment by MangelMaxime** [comment]
Hello @johnW-ret,

Thank you for the message.

After testing, your project in the web app the warning seems to be harmless because the generated code is correct.

I created a separate issue for tracking yours: https://github.com/glutinum-org/cli/issues/205

I didn't try with the published version of the CLI tool yet.

**Comment by MangelMaxime** [comment]
New version of Glutinum is now able to transform VS Code.
