### ISSUE TITLE
Unsupported kind 272 & Unsupported kind 173

### ISSUE THREAD

**Issue by nojaf** [glutinum-org/cli#24]
I tried to run this against [@firebase/app](https://www.npmjs.com/package/@firebase/app):

    npx @glutinum/cli node_modules/@firebase/app/dist/app.d.ts

```
npx @glutinum/cli node_modules/@firebase/app/dist/app.d.ts 
Generating binding file for node_modules/@firebase/app/dist/app.d.ts
readNode: Unsupported kind 272
readNode: Unsupported kind 272
readNode: Unsupported kind 272
readNode: Unsupported kind 272
readNode: Unsupported kind 272
readNode: Unsupported kind 272
readNode: Unsupported kind 272
readNode: Unsupported kind 272
file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/Glutinum.Converter/Reader/NamedDeclaration.js:30
            throw new Error(`tryReadNamedDeclaration: Unsupported kind ${declaration.kind}`);
                  ^

Error: tryReadNamedDeclaration: Unsupported kind 173
    at readNamedDeclaration (file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/Glutinum.Converter/Reader/NamedDeclaration.js:30:19)
    at Glutinum.Converter.Reader.Types.TypeScriptReader.ReadNamedDeclaration2A58F896 (file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/Glutinum.Converter/Reader/TypeScriptReader.js:69:20)
    at file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/Glutinum.Converter/Reader/InterfaceDeclaration.js:6:131
    at file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/fable_modules/fable-library.4.5.0/List.js:581:34
    at fold (file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/fable_modules/fable-library.4.5.0/List.js:363:15)
    at map (file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/fable_modules/fable-library.4.5.0/List.js:580:18)
    at readInterfaceDeclaration (file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/Glutinum.Converter/Reader/InterfaceDeclaration.js:6:21)
    at Glutinum.Converter.Reader.Types.TypeScriptReader.ReadInterfaceDeclaration1CB6FA10 (file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/Glutinum.Converter/Reader/TypeScriptReader.js:41:37)
    at readNode (file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/Glutinum.Converter/Reader/Node.js:14:111)
    at Glutinum.Converter.Reader.Types.TypeScriptReader.ReadNode6C0FD055 (file:///tmp/@glutinum/cli@latest--bunx/node_modules/@glutinum/cli/dist/Glutinum.Converter/Reader/TypeScriptReader.js:49:20)

Node.js v18.16.1
```

This might be the first experience for a lot of people, so you may want to think about the meta aspect here. What is the expected conversation here? I report stuff and expect you to fix it? That seems the more likely case, as there is no documentation at first glance of how this tool works. However, if 20 people open a problem like this, can we really expect you to solve all these for free?

Anyway, what I'm trying to get at here, is that it might make sense to improve the contributor experience sooner rather than fixing the first reported bugs.

**Comment by MangelMaxime** [comment]
Thanks for reporting the issue.

Indeed, a few things were rushed in order to publish on  January 1st.

I updated the README.md, with explanations about the project architecture and philosophy as a first step. If you think some part are unclear or more explanations are needed please feel free to tell me.

**Comment by nojaf** [comment]
Thanks, the README is a good start. I still miss a good pointer on how to act on this problem.
Like, how do I easily run the `npx @glutinum/cli` from the local repository?

I'm able to piece back `| ImportDeclaration = 272` as `Unsupported kind` but I'm not quite sure how I puzzle this back to the input code. Can a range be printed here as well? That way, I can probably isolate the missing functionality into a unit test.

**Comment by MangelMaxime** [comment]
In general, what I do is I reduce the problem to a minimal size manually by trial and errors.

If you want to run a local version of `@glutinum/cli` you can run `./build.sh cli [--watch]` and then you can use `node cli.js <path-to-typescript-definition>`.

Printing a range should be possible I think we have access to `pos` and `getText()` from the TypeScript checker.

**Comment by MangelMaxime** [comment]
I added a note mentioning that you can use `JavaScript Debug Terminal` from VSCode to debug the code too.

https://github.com/glutinum-org/cli#debugging

**Comment by MaxWilson** [comment]
I too got a 173 when trying to convert react-konva.

**Comment by MangelMaxime** [comment]
I confirm this is possible to give more context about the error.

Here an example for replacing `tryReadNamedDeclaration: Unsupported kind 173`

It gives:

- the name of the file and position
- Actual text of the node failing
- Text of the parent to give us more context in the code

```
Error while reading named declaration in
  /Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/tests/specs/interfaces/indexSignature/numberParameter.d.ts(1,31)
  
  --- Text ---
  
      [index: number]: string;
  ---
  
  --- Parent text ---
  export interface StringArray {
      [index: number]: string;
  }
  ---
              
      at readNamedDeclaration (/Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Reader/NamedDeclaration.fs:100:9)
      at variableStatement (/Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Reader/TypeScriptReader.fs:86:13)
      at <anonymous> (/Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Reader/InterfaceDeclaration.fs:16:21)
      at file:///Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/tests/fable_modules/fable-library.4.5.0/List.js:581:34
      at fold (file:///Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/tests/fable_modules/fable-library.4.5.0/List.js:363:15)
      at map (file:///Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/tests/fable_modules/fable-library.4.5.0/List.js:580:18)
      at readInterfaceDeclaration (/Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Reader/InterfaceDeclaration.fs:16:12)
      at functionDeclaration (/Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Reader/TypeScriptReader.fs:50:13)
      at readNode (/Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Reader/Node.fs:16:9)
      at moduleDeclaration (/Users/mmangel/Workspaces/Github/glutinum-org/Glutinum.Converter/src/Glutinum.Converter/Reader/TypeScriptReader.fs:60:58)
```

I am working on applying the same philosophy everywhere. If you think there are more useful information that we should try to give please feel free to comment :)

**Comment by MaxWilson** [comment]
@MangelMaxime what would be the next step after the context is known? Would I propose a possible translation in F#, and then (if approved) submit a PR? Or just jump straight to an attempted implementation/draft PR as an aid to discussion?

**Comment by MangelMaxime** [comment]
I think it is best to open an issue using the `TypeScript to F# structure conversion` templates.

It will helps us review the possible translation in F# and also assigned the issue to you. Trying to avoid having multiple people  working on the same things.

**Comment by MangelMaxime** [comment]
I just tested passing the `@firebase/app/dist/app.d.ts` throught Glutinum and the reported warning are not present anymore so I will close this issue.

If there are some incorrect translation done, please feel free to open new issues.

**Comment by nojaf** [comment]
Thanks Maxime, the output is shaping up!
